#mysql数据库
mybatis:
  type-aliases-package: com.neo.model
spring:
  application:
    name: MAApplication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    hikari:
      pool-name: MysqlDataSourcePool
      minimum-idle: 10
      maximum-pool-size: 60
      max-lifetime: 120000
      auto-commit: false
      idle-timeout: 30000
      connection-timeout: 60000
      connection-test-query: select 1


